#!/bin/bash

yes | apt-get install virtualbox-guest-additions-iso
yes apt-get install libxss1 libappindicator1 libindicator7
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
dpkg -i google-chrome*.deb
yes | apt-get install -f
dpkg -i google-chrome*.deb
rm -rf google*
yes | apt purge firefox abiword gnumeric transmission* audacious pidgin mtpaint
